# These are supported funding model platforms

github: # Replace with your GitHub Sponsors username, e.g. nkrider7
open_collective: # Replace with your Open Collective slug
buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# custom: ["https://example.com/donate"]
